# Generated by Django 3.0.5 on 2020-04-19 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_musician_net_worth'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='artist_bio',
            field=models.CharField(default=0, max_length=350),
        ),
    ]
